### ISSUE TITLE
The difference with existed method? such as LDAK(LD score regression), GCTA(REML)

### ISSUE THREAD

**Issue by Junjun-Xu** [xiaoguanghuan123/maize_eGWAS#1]
Hi

I'm new to this and would appreciate your help.
There are many ways (LDAK, GCTA) to calculate heritability at present, but I don't know the advantages of using lme4. Using the REML method, I can remove the population structure of the genotype, the hidden factors of the expression data, and the known interference factors. Have you considered these covariances? 
The other one is why you chose the repeated genotype, can you provide me with an example file?

I will be very grateful if I can get your reply as soon as possible.
Thanks

**Comment by xiaoguanghuan123** [comment]
Hi Junjun, 

First, you are right that there are many ways to calculate heritability. I didn't compare these available tools but there is no reason to choose one package over others as long as the standard approach for broad sense heritability calculation is followed. 

What we are calculating is broad-sense heritability: sigma(gt)/(sigma(gt) + sigma(env)), which means you need two or more reps of the same genotypes to observe within- and cross-genotype phenotypic variances. 

Usually, broad sense heritability calculation based on field trials includes effects from year by environment interaction, however, for our case, we were growing the seedlings in a strictly controlled environment (please see M&M section of the paper) to minimized this effect, therefore, we just fit the expression data into a mixed linear model y = gt + e with no additional covariates. 

The input file can be found here : https://figshare.com/articles/dataset/FPKM_of_19_565_genes_profiled_from_the_root_tissues_of_340_maize_genotypes_replicated_genotypes_were_either_averaged_or_kept_raw/19164584?file=34050356

Please let me know if you have additional questions.
Thanks,
Guangchao

**Comment by Junjun-Xu** [comment]
Hi Guangchao,

Thank you very much for your reply. I understand and have no question.

Thanks.
Jun

**Comment by xiaoguanghuan123** [comment]
Glad your question has been addressed. 
Best,
Guangchao
